import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useLang } from "../context/LangContext";
import { places } from "../data/places";
import Photo from "./Photo";
import MapBackground from "./MapBackground";

const FILTERS = [{ id: "all", key: "filter_all", color: "#e9e2d1" }, { id: "nature", key: "filter_nature", color: "#35804d" }, { id: "lake", key: "legend_lakes", color: "#2794bf" }, { id: "history", key: "filter_history", color: "#df8535" }, { id: "archaeology", key: "filter_archaeology", color: "#8061b9" }, { id: "quest", key: "filter_quest", color: "#e4b530" }];
function colorFor(place) { return place.type?.en?.toLowerCase().includes("lake") ? "#2794bf" : FILTERS.find((item) => item.id === place.category)?.color || "#35804d"; }

export default function SaryarkaMap({ initialSelected = null, height = "h-[470px] sm:h-[560px] lg:h-[680px]" }) {
  const { t, l } = useLang(); const [filter, setFilter] = useState("all"); const [selectedId, setSelectedId] = useState(initialSelected);
  const selected = places.find((place) => place.id === selectedId);
  const visible = useMemo(() => filter === "all" ? places : filter === "quest" ? places.filter((place) => place.hasQuest) : filter === "lake" ? places.filter((place) => place.type?.en?.toLowerCase().includes("lake")) : places.filter((place) => place.category === filter), [filter]);
  const route = places.filter((place) => place.hasQuest).map((place) => place.coords);
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_24rem]"><div className={`relative overflow-hidden rounded-[2rem] border border-[var(--color-line)] bg-[#edf1ec] shadow-[0_12px_35px_rgba(31,49,34,.08)] ${height}`}><MapBackground questRoute={route} />
    <svg className="pointer-events-none absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M17 29 L28 19 L42 15 L55 18 L68 14 L83 23 L89 39 L84 52 L89 66 L78 79 L59 84 L43 78 L28 82 L15 69 L11 51 Z" fill="rgba(244,239,217,.72)" stroke="#49633d" strokeWidth=".65" strokeLinejoin="round" /><path d="M20 62 C33 53 44 65 54 56 S73 42 85 49" fill="none" stroke="#6fa9ba" strokeWidth=".45" opacity=".75" /><path d="M25 31 C34 26 42 25 51 30 S69 35 80 29 M20 45 C33 39 41 45 51 41 S67 35 84 40 M20 69 C34 64 44 73 55 67 S72 62 83 68" fill="none" stroke="#8a9b77" strokeWidth=".22" opacity=".8" /><text x="15" y="23" fontSize="2.2" fill="#526547" fontFamily="serif" letterSpacing=".5">SARYARKA</text><text x="42" y="89" fontSize="1.7" fill="#687364" fontFamily="sans-serif">CENTRAL KAZAKHSTAN</text><polyline points={route.map((point) => point.join(",")).join(" ")} fill="none" stroke="#E4B530" strokeWidth=".55" strokeDasharray="1.2 1.2" /></svg>
    <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(135deg,rgba(255,255,255,.08),transparent_55%,rgba(29,57,34,.14))]" /><div className="pointer-events-none absolute left-4 top-4 rounded-xl border border-white/70 bg-white/85 px-3 py-2 text-xs font-bold text-[var(--color-ink)] shadow-sm backdrop-blur">SARYARKA · REGIONAL ATLAS</div>
    {visible.map((place) => <button key={place.id} onClick={() => setSelectedId(place.id)} style={{ left: `${place.coords[0]}%`, top: `${place.coords[1]}%`, backgroundColor: colorFor(place) }} className="absolute z-10 grid h-9 w-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-[3px] border-white text-white shadow-md transition-transform hover:scale-110 focus:scale-110" aria-label={l(place.name)}><span className="h-2.5 w-2.5 rounded-full bg-white" /><span className="pointer-events-none absolute left-1/2 top-10 w-max -translate-x-1/2 whitespace-nowrap text-xs font-bold text-[var(--color-ink)] drop-shadow-[0_1px_1px_rgba(255,255,255,.9)]">{l(place.name)}</span></button>)}
    {selected && <div className="absolute left-1/2 top-[42%] z-20 w-[min(23rem,calc(100%-2rem))] -translate-x-1/2 rounded-2xl bg-white p-4 shadow-[0_18px_45px_rgba(0,0,0,.22)] sm:p-5"><button onClick={() => setSelectedId(null)} className="absolute right-3 top-2 z-10 grid h-7 w-7 place-items-center rounded-full bg-white text-xl leading-none text-[var(--color-ink-soft)]" aria-label={t("close")}>×</button><Photo id={selected.id} alt="" className="h-32 w-full rounded-lg" /><h3 className="mt-4 font-display text-xl font-semibold text-[var(--color-ink)]">{l(selected.name)}</h3><p className="mt-3 text-sm leading-relaxed text-[var(--color-ink-soft)] line-clamp-2">{l(selected.short)}</p><p className="mt-2 text-xs font-semibold text-[var(--color-steppe)]">{l(selected.region)} · {l(selected.type)}</p><Link to={`/places/${selected.id}`} className="mt-4 inline-block text-sm font-bold text-[var(--color-lake)] hover:underline">{t("read_more")}</Link></div>}</div>
    <aside className="space-y-4"><div className="rounded-[2rem] border border-[var(--color-line)] bg-white p-6 shadow-sm"><p className="font-mono text-[11px] font-bold uppercase tracking-[.16em] text-[var(--color-steppe)]">Field guide</p><h2 className="mt-2 font-display text-xl font-semibold text-[var(--color-ink)]">{t("legend_title")}</h2><div className="mt-4 space-y-2">{FILTERS.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-base font-semibold transition-colors ${filter === item.id ? "bg-[var(--color-cream-dim)] text-[var(--color-ink)]" : "text-[var(--color-ink-soft)] hover:bg-[var(--color-cream)]"}`}><span className="h-3 w-3 rounded-full ring-2 ring-white" style={{ backgroundColor: item.color }} />{t(item.key)}</button>)}</div></div><div className="rounded-[1.6rem] border border-[var(--color-line)] bg-[var(--color-cream-dim)] p-5 text-sm leading-relaxed text-[var(--color-ink-soft)]">{t("select_marker_hint")}</div></aside>
  </div>;
}
